### ISSUE TITLE
2020-03-16

### ISSUE THREAD

**Issue by risacan** [ikejirirb/reading_sinatra#1]
14ページ ~ Condition と デフォルトの条件分岐たち の手前まで

**Comment by katorie** [comment]
著者に質問した

https://twitter.com/katorie/status/1234482532957032454?s=20

**Comment by katorie** [comment]
「束縛」と出会った本
「つくって学ぶプログラミング言語 RubyによるScheme処理系の実装」
https://tatsu-zine.com/books/scheme-in-ruby

**Comment by nappan23** [comment]
# 感想
- `束縛` とはなにか？がわからなかった
https://ja.wikipedia.org/wiki/%E6%9D%9F%E7%B8%9B_(%E6%83%85%E5%A0%B1%E5%B7%A5%E5%AD%A6)

=> こうしてみると難しいけど、難しく考えず…
`紐付けて、縛ること` と考える


- `束縛` から、かとりえさんが下記の本を教えてくれた！
https://tatsu-zine.com/books/scheme-in-ruby

ちょうど他の人にもLISPを勉強すると良いと教わっていたから、この本は良さそう

**Comment by risacan** [comment]
`束縛` という言葉に引きずられすぎた。
日本語から英語にして、英語を日本語にしたら、かんたんな言葉になったから、理解できた 👍
