### ISSUE TITLE
2020-04-13

### ISSUE THREAD

**Issue by risacan** [ikejirirb/reading_sinatra#2]
# 14ページ 「Condition と デフォルトの条件分岐たち」  から

**Comment by risacan** [comment]
* UnboundMethod むずかしい 😖

**Comment by katorie** [comment]
メタプロRuby97ページに返って、UnboundeMethodを復習した

**Comment by nappan23** [comment]
`UnboundMethod` を完全に忘れていた
=> メタプロ本の4章を読んで復習した！

**Comment by nappan23** [comment]
`!` を `bang` と読むこともあると知った

**Comment by katorie** [comment]
`get` `'/'` `ブロックのなかみ` をまるっと保存しているやつ

**Comment by nappan23** [comment]
コンソールで開くときとSinatraをrequireしたときはコンテキストが違う

**Comment by risacan** [comment]
![](https://media.giphy.com/media/USAWYYXiq9Ka4/giphy.gif)
