### ISSUE TITLE
2020/05/11

### ISSUE THREAD

**Issue by risacan** [ikejirirb/reading_sinatra#4]
P20 コンテキストの再確認

**Comment by nappan23** [comment]
`Sinatraアプリケーションの構築` を読み終わった！

**Comment by risacan** [comment]
* settings やばい
* Reading sintaraを失くしちゃったかも 😭 
* plugin を読み込むための register 
* `middleware` each の `c` はどこから来たのか

**Comment by nappan23** [comment]
リクエスト/インスタンスのスコープから、アプリケーション/クラスのスコープにアクセスする方法が用意されている

**Comment by nappan23** [comment]
`register` はGemを読み込むときなどに使われていそう
mustacheとか？

**Comment by kasumi8pon** [comment]
これで、リクエスト/インスタンスから、 settings が見られる！

```ruby
def self.settings
  self
end

def settings
  self.class.settings
end
```

**Comment by nappan23** [comment]
`on the fly` = 急いで
https://ejje.weblio.jp/content/on+the+fly
